name: Parameters Sets

on:
    push:
        branches:
            - master

jobs:
    parameters_set:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4']

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: php ecs check fixture/SomeNormalClass.php --config ecs-parameters-sets.yaml --debug
