# inspired by https://github.com/Symplify/Symplify/blob/master/.github/workflows/code_checks.yaml
name: Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    run:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4']

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: bin/ecs --debug --ansi
