name: Run as Composer Dependency

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    run_as_composer_dependency:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none
            -
                run: |
                    # prepare
                    mkdir standalone
                    cd standalone
                    # wait for deploy to packagist
                    sleep 30

                    # run
                    composer require symplify/easy-coding-standard-prefixed:@dev --dev
                    bin/ecs --debug
