name: Run with Set

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'PSR 12'
                        run: php ecs check fixture/SomeNormalClass.php --set psr12 --debug --ansi

                    -
                        name: 'Symplify'
                        run: php ecs check fixture/SomeNormalClass.php --set symplify --debug --ansi

                    -
                        name: 'ECS Parameters Sets'
                        run: php ecs check fixture/SomeNormalClass.php --config ecs-parameters-sets.yaml --debug --ansi

        name: Running Set ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}
