name: Run PHAR with Set Symplify

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    run_phar_with_set:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: php ecs check fixture/SomeNormalClass.php --set symplify --debug
